name=BlockNot
version=3.1.0
author=Michael Sims <sims.mike@gmail.com>
maintainer=Michael Sims <sims.mike@gmail.com>
sentence=BlockNot gives you non-blocking timers with simplicity.
paragraph=*** Version 3.1.0 is a major re-write of all of the back end code. BlockNot is now FASTER than it has ever been. The README has been completely updated and is now a thoroughly accurate document. https://github.com/EasyG0ing1/BlockNot
category=Timing
url=http://github.com/EasyG0ing1/BlockNot
architectures=*
includes=BlockNot.h
